export const iconsData = [
    {name: "Exercise.png", id:0},
    {name: "Pushups.png", id:1},
    {name: "Deadlift.png", id:2},
    {name: "Running.png", id:3},
    {name: "Sit Ups.png", id:4},
    {name: "Cycling Mountain Bike.png", id:5},
    {name: "Treadmill.png", id:6},
    {name: "Pilates.png", id:7},
    {name: "Cycling Mountain Bike-1.png", id:8},
    {name: "Spinning.png", id:9},
    {name: "Barbell.png", id:10},
    {name: "Dumbbell.png", id:11},
    {name: "Weightlifting.png", id:12},
    {name: "Staircase.png", id:13},
    {name: "Squats.png", id:14},
    {name: "Learning.png", id:15},
    {name: "Swimmer.png", id:16},
    {name: "Bench Press.png", id:17},
    {name: "Pullups.png", id:18},
    {name: "Rowing Machine.png", id:19},
]